const englishKey = [
  { number: 0, small: 'a', big: 'A' },
  { number: 1, small: 'b', big: 'B' },
  { number: 2, small: 'c', big: 'C' },
  { number: 3, small: 'd', big: 'D' },
  { number: 4, small: 'e', big: 'E' },
  { number: 5, small: 'f', big: 'F' },
  { number: 6, small: 'g', big: 'G' },
  { number: 7, small: 'h', big: 'H' },
  { number: 8, small: 'i', big: 'I' },
  { number: 9, small: 'j', big: 'J' },
  { number: 10, small: 'k', big: 'K' },
  { number: 11, small: 'l', big: 'L' },
  { number: 12, small: 'm', big: 'M' },
  { number: 13, small: 'n', big: 'N' },
  { number: 14, small: 'o', big: 'O' },
  { number: 15, small: 'p', big: 'P' },
  { number: 16, small: 'q', big: 'Q' },
  { number: 17, small: 'r', big: 'R' },
  { number: 18, small: 's', big: 'S' },
  { number: 19, small: 't', big: 'T' },
  { number: 20, small: 'u', big: 'U' },
  { number: 21, small: 'v', big: 'V' },
  { number: 22, small: 'w', big: 'W' },
  { number: 23, small: 'x', big: 'X' },
  { number: 24, small: 'y', big: 'Y' },
  { number: 25, small: 'z', big: 'Z' },
];

const numberKey = [
  { number: 0, name: '0' },
  { number: 1, name: '1' },
  { number: 2, name: '2' },
  { number: 3, name: '3' },
  { number: 4, name: '4' },
  { number: 5, name: '5' },
  { number: 6, name: '6' },
  { number: 7, name: '7' },
  { number: 8, name: '8' },
  { number: 9, name: '9' },
];

const symbolKey = [
  { number: 0, name: '~' },
  { number: 1, name: '!' },
  { number: 2, name: '@' },
  { number: 3, name: '#' },
  { number: 4, name: '$' },
  { number: 5, name: '.' },
  { number: 6, name: ',' },
  { number: 7, name: '%' },
  { number: 8, name: '^' },
  { number: 9, name: '&' },
  { number: 10, name: '*' },
  { number: 11, name: '?' },
  { number: 12, name: ';' },
  { number: 13, name: '。' },
  { number: 14, name: '、' },
  { number: 15, name: '+' },
  { number: 16, name: '=' },
  { number: 17, name: '-' },
  { number: 18, name: '_' },
  { number: 19, name: ':' },
  { number: 20, name: '(' },
  { number: 21, name: ')' },
  { number: 22, name: '|' },
  { number: 23, name: '\\' },
  { number: 24, name: '-' },
  { number: 25, name: '"' },
  
];

export default {
  englishKey,
  numberKey,
  symbolKey,
};
